config/routes.rb
Rails.application.routes.draw do
	# root routes
	authenticated :user do
		root to: 'users#travel_records', as: :authenticated_root
	end
	root to: "welcome#index"

	# standalone routes
	get "how-it-works", to: "welcome#how_it_works"
	get "wiki", to: "welcome#wiki"

	# model routes
	get "countries", to: "countries#index"
	get "update_country", to: "countries#update"

	devise_for :users
	resources :users do
		member do
			get "travel_records"
			get "big_map"
			get "match"
			post "create_update_country_travel_record", to: "country_travel_records#create_update"
			get "follow"
	    	get "unfollow"
	    	get "my_connections"
		end
	end

	resources :country_travel_records
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime
#  updated_at             :datetime
#  firstname              :string
#  lastname               :string
#  about                  :text
#  country                :string
#  city                   :string
#  age                    :integer
#  gender                 :string
#  role                   :string
#  slug                   :string
#  avatar_file_name       :string
#  avatar_content_type    :string
#  avatar_file_size       :integer
#  avatar_updated_at      :datetime
#  delete_avatar          :boolean
#

class User < ActiveRecord::Base
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
	     :recoverable, :rememberable, :trackable, :validatable

	has_many :country_travel_records

  	# gem paperclip	     
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, 
								default_url: ":style/default.gif"
	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  	# gem friendly_id
	extend FriendlyId
	friendly_id :slug_candidates, use: :slugged
	def slug_candidates
	[
	  [:firstname, :lastname],
	  [:firstname, :lastname, :country],
	  [:firstname, :lastname, :country, :city],
	]
	end

	# gem acts_as_follower
	acts_as_followable
	acts_as_follower




   	def fullname
   		if self.firstname.blank? and self.lastname.blank?
   			""
   		elsif self.firstname.blank?
   			"#{self.lastname}"
   		elsif self.lastname.blank?
   			"#{self.firstname}"
   		else
 			"#{self.firstname} #{self.lastname}"
 		end
 	end


	def find_country_travel_record(country)
		self.country_travel_records.each do |record|
	  		if record.country_id == country.id
	  			@is_found = true;
	  			@country_travel_record_id = record.id
	    	end
	    end
	    if @is_found
	    	@country_travel_record_id
	    else
	    	nil
	    end	
	end

	def country_travel_records_wannavisit
		CountryTravelRecord.where(user_id: self.id, travel_status: "wannavisit").order("country_id ASC")
	end

	def country_travel_records_havebeen
		CountryTravelRecord.where(user_id: self.id, travel_status: "havebeen").order("country_id ASC")
	end

	def have_added_country(country)
		have_added =  false
		CountryTravelRecord.where(user_id: self.id).each do |record|
			have_added = true if record.country_id == country.id
		end

		have_added
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_user, only: [:show, :edit, :update, :match, :big_map, :follow, :unfollow]
  before_action :format_params, only: [:update]

  def show
    # display country travel records on map
    @hash_country_travel_records = build_country_travel_records_hash(@user)
  end

  def edit
  end

  def update
    authorize! :update, @user

    @user.slug = nil
    if @user.update(@formatted_params)
        
        # check if user wants to delete avatar  
        if @formatted_params[:delete_avatar] == "true"
          @user.avatar = nil
          @user.save
        end
      
      flash[:notice] = "Profile updated."
      redirect_to @user
    else
      render 'edit'
    end
  end

  def travel_records
    @user = current_user

    @countries = Country.all.order("country_name ASC")
    @countries_in_asia = Country.in_asia.order("country_name ASC")
    @countries_in_europe = Country.in_europe.order("country_name ASC")
    @countries_in_northamerica = Country.in_northamerica.order("country_name ASC")
    @countries_in_southamerica = Country.in_southamerica.order("country_name ASC")
    @countries_in_africa = Country.in_africa.order("country_name ASC")
    @countries_in_oceania = Country.in_oceania.order("country_name ASC")
    @countries_in_antarctica = Country.in_antarctica.order("country_name ASC")

    @countries_search_results = Country.text_search(params[:search]).order("country_name ASC")

    # display country travel records on map
    @hash_country_travel_records = build_country_travel_records_hash(@user)

  end

  def match
    @array_country_travel_records_both_wannavisit = 
      current_user.country_travel_records_wannavisit.pluck("country_id") & 
      @user.country_travel_records_wannavisit.pluck("country_id")
    
    @array_country_travel_records_i_wannavisit_friend_havebeen = 
      current_user.country_travel_records_wannavisit.pluck("country_id") &
      @user.country_travel_records_havebeen.pluck("country_id")
    
    @array_country_travel_records_i_havebeen_friend_wannavisit = 
      current_user.country_travel_records_havebeen.pluck("country_id") &  
      @user.country_travel_records_wannavisit.pluck("country_id")


    @travel_match_score = (@array_country_travel_records_both_wannavisit.size.to_f / 
                            current_user.country_travel_records_wannavisit.size * 100).round(2)
  
  end

  def big_map
    # display country travel records on map
    @hash_country_travel_records = build_country_travel_records_hash(@user)
  end

  def follow
    current_user.follow(@user)
    flash[:notice] = "Following #{@user.fullname} now."
    redirect_to @user
  end

  def unfollow
    current_user.stop_following(@user)
    flash[:alert] = "Stopped following #{@user.fullname}."
    redirect_to @user
  end

  def my_connections
    @user = current_user
  end

  private
  
  def user_params
    params.require(:user).permit(:firstname, :lastname, :about, :country, :city, :age, :gender, :avatar, :delete_avatar, :search)
  end

  def set_user   
    @user = User.friendly.find(params[:id])
  end
  
  def format_params
    @formatted_params = user_params
    
    # if capitalizing names and cities
    @formatted_params[:firstname] = capitalize_input(@formatted_params[:firstname])
    @formatted_params[:lastname] = capitalize_input(@formatted_params[:lastname])
    @formatted_params[:city] = capitalize_input(@formatted_params[:city])

    # if using gem auto_html
    # @formatted_params[:about] = auto_html(@formatted_params[:about]){ simple_format; link(target: 'blank') }
    # @formatted_params[:about] = @formatted_params[:about][3..(@formatted_params[:about].length-5)] if !@formatted_params[:about].empty?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_continent_tabs.html.erb
<div role="tabpanel">
  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation"><a href="#asia" class="active" aria-controls="asia" role="tab" data-toggle="tab">Asia</a></li>    
    <li role="presentation"><a href="#europe" aria-controls="europe" role="tab" data-toggle="tab">Europe</a></li>
    <li role="presentation"><a href="#northamerica" aria-controls="northamerica" role="tab" data-toggle="tab">N. America</a></li>
    <li role="presentation"><a href="#southamerica" aria-controls="southamerica" role="tab" data-toggle="tab">S. America</a></li>
    <li role="presentation"><a href="#africa" aria-controls="africa" role="tab" data-toggle="tab">Africa</a></li>
    <li role="presentation"><a href="#oceania" aria-controls="oceania" role="tab" data-toggle="tab">Oceania</a></li>
    <li role="presentation"><a href="#antarctica" aria-controls="antarctica" role="tab" data-toggle="tab">Antarctica</a></li>
    <!-- <li role="presentation"><a href="#search" aria-controls="search" role="tab" data-toggle="tab">Search</a></li> -->
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">

    <div role="tabpanel" class="tab-pane active" id="asia">
      <div class="container-country-tab">
        <%= render @countries_in_asia %>
      </div>
    </div>

    <div role="tabpanel" class="tab-pane" id="europe">
      <div class="container-country-tab">
        <%= render @countries_in_europe %>
      </div>      
    </div>
    
    <div role="tabpanel" class="tab-pane" id="northamerica">
      <div class="container-country-tab">
        <%= render @countries_in_northamerica %>
      </div>      
    </div>
    
    <div role="tabpanel" class="tab-pane" id="southamerica">    
      <div class="container-country-tab">
        <%= render @countries_in_southamerica %>
      </div>        
    </div>

    <div role="tabpanel" class="tab-pane" id="africa">
      <div class="container-country-tab">
        <%= render @countries_in_africa %>
      </div>        
    </div>
    
    <div role="tabpanel" class="tab-pane" id="oceania">
      <div class="container-country-tab">
        <%= render @countries_in_oceania %>
      </div>      
    </div>
    
    <div role="tabpanel" class="tab-pane" id="antarctica">
      <div class="container-country-tab">
        <%= render @countries_in_antarctica %>
      </div>
    </div>


    <div role="tabpanel" class="tab-pane" id="search">
      <div class="search-country">     
        <p>Search for a country:</p>
        <%= form_tag travel_records_user_path(current_user), class: "form-inline", method: :get do %>
          <%= text_field_tag :search, params[:search], class: "form-control margin-search-action" %>
          <%= submit_tag "Search", class: "btn btn-primary btn-sm margin-search-action" %>
        <% end %>
      </div>

      <% if !params[:search].blank? %>
        <% if @countries_search_results.blank? %>
          <p>No such country.</p>
        <% else %>
          <%= render @countries_search_results %>
        <% end %>
      <% end %>     
    </div>

  </div>
</div>

app/views/users/_countries_havebeen.html.erb
<div class="country-block">
  <p class="inline"><%= record.country.country_name %></p>
  <p class="country-buttons inline">
    <% if record.user == current_user %>
        <%= link_to "I wanna visit!", create_update_country_travel_record_user_path(id: current_user.id, country_id: record.country.id, travel_status: "wannavisit"), class: "btn btn-success btn-xs", method: :post, remote: true %>&nbsp;
        <%= link_to "Remove", country_travel_record_path(record), method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-warning btn-xs", remote: true %>
      <% end %>
  </p>
</div>

app/views/users/_countries_wannavisit.html.erb
<div class="country-block">
	<p class="inline"><%= record.country.country_name %></p>
	<p class="country-buttons inline">
		<% if record.user == current_user %>
		  	<%= link_to "I've been there!", create_update_country_travel_record_user_path(id: current_user.id, country_id: record.country.id, travel_status: "havebeen"), class: "btn btn-success btn-xs", method: :post, remote: true %>&nbsp;
		  	<%= link_to "Remove", country_travel_record_path(record), method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-warning btn-xs", remote: true %>
	  	<% end %>
	</p>
</div>

app/views/users/_follow_avatar.html.erb
<div class="container-avatar-follow inline">
	<div class="avatar-friend-list aligned-center"><%= link_to (image_tag user.avatar.url(:thumb)), user %></div>
	<div class="avatar-name aligned-center"><%= link_to user.firstname, user %></div>
</div>

app/views/users/_friend_avatar.html.erb
<div class="container-avatar-friend inline">
	<div class="avatar-friend-list"><%= link_to (image_tag user.avatar.url(:thumb)), user %></div>
	<div class="avatar-name"><%= link_to user.firstname, user %></div>
	<%= link_to 'Match', match_user_path(user), class: "btn btn-warning btn-xs" %>
</div>

app/views/users/big_map.html.erb
<!-- google map -->
<div id="map_big_map"></div>

<div class="aligned-center margin-top-10px">
	<%= link_to "Back To Travel Records", travel_records_user_path(current_user), class: "btn btn-primary" %>
</div>


<!-- google map script -->
<script>

handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map_big_map'}}, function(){
	<% if @hash_country_travel_records.blank? %>
		handler.getMap().setZoom(2);

	<% elsif @hash_country_travel_records.size == 1 %>
		markers = handler.addMarkers(<%= @hash_country_travel_records.to_json.html_safe %>);
		handler.map.centerOn(markers[0]); 
		handler.getMap().setZoom(4);

	<% else %>
		markers = handler.addMarkers(<%= @hash_country_travel_records.to_json.html_safe %>);
		handler.bounds.extendWith(markers);
		handler.fitMapToBounds();

	<% end %>
});

</script>

app/views/users/edit.html.erb
<div class="container-edit">
<h1>Edit Profile</h1>
<%= render 'form' %>
</div>

app/views/users/match.html.erb
<h1>
	My Match With <%= @user.fullname %>
	<%= link_to "Back To Travel Records", travel_records_user_path(current_user), class: "btn btn-primary" %>
</h1>

<h3 class="travel-match-score bg-success text-center">Travel Match Score: <%= @travel_match_score %>%</h4>

<div class="row" id="match-lists">

	<!-- both wanna visit -->
	<div class="col-md-4">
		<div class="panel">
			<div class="panel-heading"><h4>We both wanna visit:</h4></div>
			<div class="panel-body">
				<!-- it's possible that there is no common interest. -->
				<% if @array_country_travel_records_both_wannavisit.blank? %>
					<p>No such country.</p> 
				<% else %>
					<% @array_country_travel_records_both_wannavisit.each do |id| %>
						<%= render partial: "countries/three_options", locals: { country: Country.find(id) } %>
					<% end %>
				<% end %>
			</div>
		</div>
	</div> <!-- /col -->

	<!-- i wanna visit, friend have been -->
	<div class="col-md-4">
		<div class="panel">
			<div class="panel-heading"><h4>I wanna visit and <%= @user.firstname %> has been to:</h4></div>
			<div class="panel-body">
				<% if @array_country_travel_records_i_wannavisit_friend_havebeen.blank? %>
					<p>No such country.</p> 
				<% else %>
					<% @array_country_travel_records_i_wannavisit_friend_havebeen.each do |id| %>
						<%= render partial: "countries/three_options", locals: { country: Country.find(id) } %>
					<% end %>
				<% end %>
			</div>
		</div>
	</div> <!-- /col -->

	<!-- i have been, friend wanna visit -->
	<div class="col-md-4">
		<div class="panel">
			<div class="panel-heading"><h4>I have been to and <%= @user.firstname %> wanna visit:</h4></div>
			<div class="panel-body">
				<% if @array_country_travel_records_i_havebeen_friend_wannavisit.blank? %>
					<p>No such country.</p> 
				<% else %>
					<% @array_country_travel_records_i_havebeen_friend_wannavisit.each do |id| %>
						<%= render partial: "countries/three_options", locals: { country: Country.find(id) } %>
					<% end %>
				<% end %>
			</div>
		</div>
	</div> <!-- /col -->


</div> <!-- /row -->




<!-- modal popup -->
<div class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <i class="fa fa-times fa-2x"></i>
        </button><br>   
      </div>
      <div class="modal-body">
        <iframe src="" frameborder="0" width="865px;" height="500px;"></iframe>
      </div>
      <div class="modal-footer"></div>
  </div>
</div>

app/views/users/show.html.erb
<%if @user == current_user %>
	<h1>
    My Profile
    <%= link_to 'Edit Profile', edit_user_path, class: "btn btn-warning btn-sm" %>
  </h1>
<% else %>
  <% if @user.firstname.blank? and @user.lastname.blank? %>
	  <h1>User Profile</h1>
  <% else %>
    <h1><%= @user.fullname %>'s Profile</h1>
  <% end %>
<% end %>

<div class="row">
  <div class="col-md-4">
    <div class="panel panel-profile">
      
      <div class="row">
        <div class="col-md-4">
          <div class="container-profile-avatar-follow">
          
            <div class="avatar-profile">
              <%= image_tag @user.avatar.url(:medium) %>
            </div>
          
            <div class="btn-follow-unfollow">
              <% if @user.followers.include?(current_user) %>
                <%= link_to 'Unfollow', unfollow_user_path(@user), class: "btn btn-danger btn-sm" %>
              <% elsif current_user!= @user %>
                <%= link_to 'Follow', follow_user_path(@user), class: "btn btn-success btn-sm" %>
              <% end %>
            </div>
            
          </div> <!-- /box -->
        
        </div> <!-- /col -->
        
        <div class="col-md-8">
          <div class="profile-table">
            <table>
              <!-- display email and edit login only if user views oneself -->
              <%if @user == current_user %>
                <tr>
                  <td><strong>Login email:</strong></td> 
                  <td><%= @user.email %></td>
                </tr>
                <tr>
                  <td></td>
                  <td>      
                    <% if @user == current_user %>
                      <%= link_to ("Edit Login <span class='glyphicon glyphicon-edit'></span>").html_safe, edit_user_registration_path, class: "btn btn-warning btn-xs" %>
                    <% end %>
                  </td>
              </tr>
              <tr><td>&nbsp;</td><td></td></tr>
              <% end %>

              <tr>
                <td><strong>First name:</strong></td>
                <td><%= @user.firstname %></td>
              </tr>
              <tr>
                <td><strong>Last name:</strong></td>
                <td><%= @user.lastname %></td>
              </tr>
              <tr>
                <td><strong>Country:</strong></td>
                <td><%= @user.country %></td>
              </tr>
              <tr>
                <td><strong>City:</strong> </td>
                <td<%= @user.city %>></td>
              </tr>
              <tr>
                <td><strong>Gender:</strong></td>
                <td><%= @user.gender %></td>
              </tr>
              <tr>
                <td><strong>Age:</strong></td>
                <td><%= @user.age %></td>
              </tr>
              <tr>
                <td><strong>About me:</strong></td>
                <td><%= @user.about %></td>
              </tr>
            </table>   
          </div>           
        </div> <!-- /col -->
      </div> <!-- /row -->
    </div> <!-- /panal -->



    <!-- followers and following -->
    <div class="panel panel-follow">
      <p><strong>Followed by:</strong></p> 
      <% @user.followers.each do |follower| %>
        <%= render partial: "users/follow_avatar", locals: { user: follower} %>
      <% end %>
    </div>

    <div class="panel panel-follow">
      <p><strong>Following:</strong></p> 
      <% @user.all_following.each do |following| %>
        <%= render partial: "users/follow_avatar", locals: { user: following} %>
      <% end %>
    </div>

  </div>
  <div class="col-md-8">
      
      <div class="panel panel-default panel-travel-map-and-list">
        <!-- google map, legend, view big map button -->
        <div id="map_countries_profile"></div>
        <div class="container-map-legend">
          <div class="inline"><%= image_tag("https://cdn0.iconfinder.com/data/icons/small-n-flat/24/678087-heart-20.png") %> countries I wanna visit </div>&nbsp;&nbsp;
          <div class="inline"><%= image_tag("https://cdn0.iconfinder.com/data/icons/small-n-flat/24/678134-sign-check-20.png") %> countries I've been to </div> 
        </div>

        <div class="container-country-travel-lists"><%= render "travel_list_tabs" %></div>
      </div>

    </div> <!-- /col -->
</div> <!-- /row -->





<!-- modal popup -->
<div class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <i class="fa fa-times fa-2x"></i>
        </button><br>   
      </div>
      <div class="modal-body">
        <iframe src="" frameborder="0" width="865px;" height="500px;"></iframe>
      </div>
      <div class="modal-footer"></div>
  </div>
</div>




<!-- google map script -->
<script>

handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map_countries_profile'}}, function(){
  <% if @hash_country_travel_records.blank? %>
    handler.getMap().setZoom(2);

  <% elsif @hash_country_travel_records.size == 1 %>
    markers = handler.addMarkers(<%= @hash_country_travel_records.to_json.html_safe %>);
    handler.map.centerOn(markers[0]); 
    handler.getMap().setZoom(4);

  <% else %>
    markers = handler.addMarkers(<%= @hash_country_travel_records.to_json.html_safe %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();

  <% end %>
});

</script>

app/views/users/travel_profile.html.erb
<h1><%= @user.fullname.blank? ? "" : "#{@user.fullname}'s " %>Travel Profile</h1>

<div class="row">
	<div class="col-md-7 smaller-gutter">	
		<!-- panel showing countries grouped by continents -->
		<div class="panel panel-success panel-countries">
			<p>
				<div class="inline"><button class="btn btn-info btn-xs round">&nbsp;<i class="fa fa-info"></i>&nbsp;</button> More Info</div>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				<div class="inline"><button class="btn btn-danger btn-xs round"><i class="fa fa-heart"></i></button> "I wanna visit!"</div>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				<div class="inline"><button class="btn btn-success btn-xs round"><i class="fa fa-check"></i></button> "I've been there!"</div>
			</p>
			<br>
			
			<%= render "continent_tabs" %>
		</div>
	</div>

	<div class="col-md-4 smaller-gutter">
		<div class="panel panel-default panel-travel-map-and-list">
			<!-- google map, legend, view big map button -->
			<div id="map_countries"></div>
			<div class="container-map-legend">
				<div class="inline"><%= image_tag("https://cdn0.iconfinder.com/data/icons/small-n-flat/24/678087-heart-20.png") %> countries I wanna visit </div>&nbsp;&nbsp;
				<div class="inline"><%= image_tag("https://cdn0.iconfinder.com/data/icons/small-n-flat/24/678134-sign-check-20.png") %> countries I've been to </div> 
			</div>
			<div class="aligned-center"><%= link_to "View Big Map", big_map_user_path(current_user), class: "btn btn-success btn-xs" %></div>

			<div class="container-country-travel-lists"><%= render "travel_list_tabs" %></div>
		</div>
	</div>

	<div class="col-md-1 smaller-gutter">
		<div class="panel panel-friend-avatars">
			<%= render "users/friend_avatar" %>
		</div>
	</div>

</div>


<!-- modal popup -->
<div class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <i class="fa fa-times fa-2x"></i>
        </button><br>   
      </div>
      <div class="modal-body">
        <iframe src="" frameborder="0" width="865px;" height="500px;"></iframe>
      </div>
      <div class="modal-footer"></div>
  </div>
</div>


<!-- google map script -->
<script>

handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map_countries'}}, function(){
	<% if @hash_country_travel_records.blank? %>
		handler.getMap().setZoom(2);

	<% elsif @hash_country_travel_records.size == 1 %>
		markers = handler.addMarkers(<%= @hash_country_travel_records.to_json.html_safe %>);
		handler.map.centerOn(markers[0]); 
		handler.getMap().setZoom(4);

	<% else %>
		markers = handler.addMarkers(<%= @hash_country_travel_records.to_json.html_safe %>);
		handler.bounds.extendWith(markers);
		handler.fitMapToBounds();

	<% end %>
});

</script>

app/views/users/travel_records.html.erb
<h1>Edit Travel Records</h1>

<div class="row">
	<div class="col-md-5 smaller-gutter">	
		<!-- panel showing countries grouped by continents -->
		<div id="country-tabs" class="panel panel-success panel-countries">			
			<%= render "continent_tabs" %>
		</div>
	</div> <!-- /col -->

	<div id="travel-records" class="col-md-7 smaller-gutter">
		
		<div class="panel panel-map">
			<!-- google map, legend, view big map button -->
			<div id="map_countries"></div>
			<div class="container-map-legend aligned-center">
				<div class="inline"><%= image_tag("heart.png") %> countries I wanna visit </div>&nbsp;&nbsp;
				<div class="inline"><%= image_tag("check.png") %> countries I've been to </div> 
			</div>
			<!-- <div class="aligned-center"><%#= link_to "View Big Map", big_map_user_path(current_user), class: "btn btn-primary btn-xs" %></div> -->

		</div> <!-- /map panel -->
		

		<div class="row">

			<!-- countries i wanna visit -->
			<div class="col-md-6 smaller-gutter">
				<div class="panel panel-travel-record-wannavisit">	
					<h4>Countries I wanna visit:</h4>
					<div id="wannavisit">
				        <% @user.country_travel_records_wannavisit.each do |record| %>
				          <%= render partial: "countries_wannavisit", locals: { record: record } %>
				        <% end %>
				    </div>
				</div>
			</div>

			<!-- countries i've been to -->
			<div class="col-md-6 smaller-gutter">
				<div class="panel panel-travel-record-havebeen">	
					<h4>Countries I have been to:</h4>
					<div id="havebeen">
				        <% @user.country_travel_records_havebeen.each do |record| %>
				          <%= render partial: "countries_havebeen", locals: { record: record } %>
				        <% end %>
			    	</div>
				</div>
			</div>

		</div> <!-- /row -->
	</div> <!-- /col -->

</div>


<!-- modal popup -->
<div class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <i class="fa fa-times fa-2x"></i>
        </button><br>   
      </div>
      <div class="modal-body">
      	<div class="loading"><%= image_tag("ajax-loader-black.gif") %></div>
        <iframe src="" frameborder="0" width="865px;" height="500px;"></iframe>
      </div>
      <div class="modal-footer"></div>
  </div>
</div>


<!-- google map script -->
<script>

handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map_countries'}}, function(){
	<% if @hash_country_travel_records.blank? %>
		handler.getMap().setZoom(2);

	<% elsif @hash_country_travel_records.size == 1 %>
		markers = handler.addMarkers(<%= @hash_country_travel_records.to_json.html_safe %>);
		handler.map.centerOn(markers[0]); 
		handler.getMap().setZoom(4);

	<% else %>
		markers = handler.addMarkers(<%= @hash_country_travel_records.to_json.html_safe %>);
		handler.bounds.extendWith(markers);
		handler.fitMapToBounds();

	<% end %>
});

</script>


<!-- current tab stays active after refreshing -->
<script>
$(document).ready(function() {
    if(location.hash) {
        $('a[href=' + location.hash + ']').tab('show');
    }
    $(document.body).on("click", "a[data-toggle]", function(event) {
        location.hash = this.getAttribute("href");
    });
});
$(window).on('popstate', function() {
    var anchor = location.hash || $("a[data-toggle=tab]").first().attr("href");
    $('a[href=' + anchor + ']').tab('show');
});
</script>