config/routes.rb
Rails.application.routes.draw do
	# root routes
	authenticated :user do
		root to: 'users#travel_records', as: :authenticated_root
	end
	root to: "welcome#index"

	# standalone routes
	get "how-it-works", to: "welcome#how_it_works"
	get "wiki", to: "welcome#wiki"

	# model routes
	get "countries", to: "countries#index"
	get "update_country", to: "countries#update"

	devise_for :users
	resources :users do
		member do
			get "travel_records"
			get "big_map"
			get "match"
			post "create_update_country_travel_record", to: "country_travel_records#create_update"
			get "follow"
	    	get "unfollow"
	    	get "my_connections"
		end
	end

	resources :country_travel_records
end

app/models/country.rb
# == Schema Information
#
# Table name: countries
#
#  id             :integer          not null, primary key
#  country_code   :string
#  country_name   :string
#  continent_name :string
#  continent_code :string
#  created_at     :datetime
#  updated_at     :datetime
#  latitude       :float
#  longitude      :float
#

class Country < ActiveRecord::Base
	has_many :country_travel_records

	scope :in_asia, -> { where(continent_name: "Asia") }
	scope :in_europe, -> { where(continent_name: "Europe") }
	scope :in_northamerica, -> { where(continent_name: "North America") }
	scope :in_southamerica, -> { where(continent_name: "South America") }
	scope :in_africa, -> { where(continent_name: "Africa") }
	scope :in_oceania, -> { where(continent_name: "Oceania") }
	scope :in_antarctica, -> { where(continent_name: "Antarctica") }

	geocoded_by :country_name
	after_validation :geocode, if: :country_name_changed? 

	include PgSearch
	pg_search_scope :search, against: :country_name

	def self.text_search(query)
		search(query)
	end

end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  def index
  	@countries = Country.all  	
  end

  def update
  	@country = Country.find(params[:id])
  	if @country.update(country_params)
  	    flash[:notice] = "Updated"
    else
		flash[:notice] = "Update failed."
	end
    
    redirect_to countries_path
  end

  private
  def country_params
    params.permit(:id)
  end
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/views/countries/_country.html.erb
<div class="country-block">
  <% if current_user.have_added_country(country) %>
    
    <p class="inline faded"><%= country.country_name %></p>
    <p class="country-buttons faded">(already added to your travel record)</p>

  <% else %>

    <p class="inline"><%= country.country_name %></p>
    <p class="country-buttons inline">
      <% if user_signed_in? %>

      	<%= link_to ("I wanna visit").html_safe, create_update_country_travel_record_user_path(id: current_user.id, country_id: country.id, travel_status: "wannavisit"), class: "btn btn-danger btn-xs", method: :post, remote: true %>&nbsp;
      	<%= link_to ("I've been there").html_safe, create_update_country_travel_record_user_path(id: current_user.id, country_id: country.id, travel_status: "havebeen"), class: "btn btn-success btn-xs", method: :post, remote: true %>&nbsp;
          <button id="wiki_<%= country.id %>" class="btn btn-info btn-xs">More Info</button>
      <% end %>
    </p>

  <% end %>
</div>

<!-- modal script -->
<script>

$("#wiki_<%= country.id %>").click(function(){

  $('.modal').on('shown.bs.modal',function(){
    $(this).find('iframe').attr('src','<%= wiki_path(country_id: country.id) %>')
  })
  
    $('.modal').modal({show:true})
    
    $('iframe').load(function() {
    $('.loading').hide();
});
    
})
</script>

app/views/countries/_country_NO-BUTTON.html.erb
<a href="" id="wiki_<%= country.id %>">&nbsp;<i class="fa fa-info"></i>&nbsp;</a>
<%= link_to ("<i class='fa fa-heart'></i>").html_safe, create_update_country_travel_record_user_path(id: current_user.id, country_id: country.id, travel_status: "wannavisit"), method: :post %>
<%= link_to ("<i class='fa fa-check'></i>").html_safe, create_update_country_travel_record_user_path(id: current_user.id, country_id: country.id, travel_status: "havebeen"), method: :post %>

app/views/countries/_three_options.html.erb
<div class="row">
  <div class="col-md-4">
	 <%= country.country_name %> 
  </div>
	
  <div class="col-md-8">
    <% if user_signed_in? %>
     
      <button id="wiki_<%= country.id %>" class="btn btn-info btn-xs round">&nbsp;<i class="fa fa-info"></i>&nbsp;</button>&nbsp;

    	<%= link_to ("<i class='fa fa-heart'></i>").html_safe, create_update_country_travel_record_user_path(id: current_user.id, country_id: country.id, travel_status: "wannavisit"), class: "btn btn-danger btn-xs round", method: :post, remote: true %>&nbsp;
    	<%= link_to ("<i class='fa fa-check'></i>").html_safe, create_update_country_travel_record_user_path(id: current_user.id, country_id: country.id, travel_status: "havebeen"), class: "btn btn-success btn-xs round", method: :post, remote: true %>&nbsp;
      <%= link_to ("<i class='fa fa-times'></i>").html_safe, country_travel_record_path(id: current_user.find_country_travel_record(country)), method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-warning btn-xs round", remote: true %>

    <% end %>
  </div>
</div>
<br>

<!-- modal script -->
<script>

$("#wiki_<%= country.id %>").click(function(){

  $('.modal').on('shown.bs.modal',function(){
    $(this).find('iframe').attr('src','<%= wiki_path(country_id: country.id) %>')
  })
  
    $('.modal').modal({show:true})
    
    $('iframe').load(function() {
    $('.loading').hide();
});
    
})
</script>

app/views/countries/index.html.erb
<h1>All Countries</h1>
<%= render @countries %>




<!-- modal popup -->
<div class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <i class="fa fa-times fa-2x"></i>
        </button><br>   
      </div>
      <div class="modal-body">
        <iframe src="" frameborder="0" width="865px;" height="500px;"></iframe>
      </div>
      <div class="modal-footer"></div>
  </div>
</div>