config/routes.rb
Rails.application.routes.draw do
	# root routes
	authenticated :user do
		root to: 'users#travel_records', as: :authenticated_root
	end
	root to: "welcome#index"

	# standalone routes
	get "how-it-works", to: "welcome#how_it_works"
	get "wiki", to: "welcome#wiki"

	# model routes
	get "countries", to: "countries#index"
	get "update_country", to: "countries#update"

	devise_for :users
	resources :users do
		member do
			get "travel_records"
			get "big_map"
			get "match"
			post "create_update_country_travel_record", to: "country_travel_records#create_update"
			get "follow"
	    	get "unfollow"
	    	get "my_connections"
		end
	end

	resources :country_travel_records
end

app/views/layouts/_logo.html.erb
<!-- Brand and toggle get grouped for better mobile display -->
<div class="navbar-header">
  <button id="nav-toggle-button-1" type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1">
    <span class="sr-only">Toggle navigation</span>
    <span class="glyphicon glyphicon-menu-hamburger" style="color:#D3D3D3; font-size:1.2em;"></span>
  </button>
  <%= link_to ("<i class='fa fa-users fa-lg'></i> BeMyTravelPartner").html_safe, root_path, class: "navbar-brand" %>
</div>

app/views/layouts/_nav_bottom.html.erb
<% if controller.class == WelcomeController && controller.action_name == 'index' %>
  <nav class="navbar navbar-fixed-bottom landing-page-menu-bottom">
<% else %>    
  <nav class="navbar navbar-inverse navbar-fixed-bottom">
<% end %>

    <div class="container-navbar-bottom ">

      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-2">
          <span class="sr-only">Toggle navigation</span>
          <span class="glyphicon glyphicon-triangle-top" style="color:#D3D3D3"></span>
        </button>
      </div>

      <div class="collapse navbar-collapse" id="navbar-collapse-2">
      <p class="navbar-text navbar-left">www.BeMyTravelPartner.com All rights reserved.</p>

    	<ul class="nav navbar-nav navbar-right">
    		<li><%= link_to'About' %></li>
    		<li><%= link_to 'Privacy Policy' %></li>
    		<li><%= link_to 'Legal Disclaimer' %></li>
    		<li><%= link_to 'Help/FAQ' %></li>
    		<li><%= link_to 'Contact' %></li>
    	</ul>
      </div> 

    </div>
  </nav>

app/views/layouts/_nav_top_not_signed_in.html.erb
<% if controller.class == WelcomeController && controller.action_name == 'index' %>
    <nav class="navbar landing-page-menu">
<% else %>
    <nav class="navbar navbar-inverse">
<% end %>

  <div class="container-fluid narrower-nav-top">

    <%= render "layouts/logo" %>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-collapse-1">
      
      <ul class="nav navbar-nav">
        
        <!-- display roll-over highlight if current page -->
        <li class=
          <% if controller.class == WelcomeController && controller.action_name == 'how_it_works' %>
            "active"
          <% end %>
        >
          <%= link_to 'How It Works', how_it_works_path %>
        </li>

        <li class=
          <% if controller.class == Devise::RegistrationsController && controller.action_name == 'new' %>
            "active"
          <% end %>
        >
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        </li>


      </ul>

      <p class="navbar-text navbar-right">
        <%= link_to 'Sign In', new_user_session_path, class: "navbar-link" %> 
      </p>


    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_nav_top_signed_in.html.erb
<% if controller.class == WelcomeController && controller.action_name == 'index' %>
    <nav class="navbar landing-page-menu">
<% else %>
    <nav class="navbar navbar-inverse">
<% end %>

  <div class="container-fluid narrower-nav-top">

    <%= render "layouts/logo" %>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-collapse-1">
      
      <ul class="nav navbar-nav">
        
        <!-- display roll-over highlight if current page -->
        <li class=
          <% if controller.class == UsersController && controller.action_name == 'travel_records' %>
            "active"
          <% end %>
        >
          <%= link_to 'Travel Records', "#{travel_records_user_path(current_user)}#asia" %>
        </li>
  
        <li class=
          <% if controller.class == UsersController && controller.action_name == 'my_connections' %>
            "active"
          <% end %>
        >
          <%= link_to 'My Connections', my_connections_user_path(current_user) %>
        </li>


          <li class=
          <% if controller.class == UsersController && controller.action_name == 'show' %>
            "active"
          <% end %>
        >
          <%= link_to 'Profile', user_path(current_user) %>
        </li>

      </ul>


  
      <p class="navbar-text navbar-right">
        <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "navbar-link" %>
      </p>
        
      <!-- display user info -->  
      <% if !current_user.fullname.blank? %>
        <p class="navbar-text navbar-right signed-in-as-link">Signed in as <%= link_to truncate("#{current_user.fullname}", length: 30), current_user %></p>
      <% elsif !current_user.email.blank? %>
        <p class="navbar-text navbar-right signed-in-as-link">Signed in as <%= link_to truncate(current_user.email, length: 30), current_user %></p>
      <% end %>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Be My Travel Partner</title>
	<%= favicon_link_tag 'favicon.ico' %>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
	<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
	<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
</head>

<body role="document" 
	<% if (controller.controller_name == "welcome" && controller.action_name == "wiki") %>
		class="modal-background" 
	<% end %>
>
	
	<!-- nav top -->
	<% if user_signed_in? %>
		<%= render "layouts/nav_top_signed_in" if !(controller.controller_name == "welcome" && controller.action_name == "wiki") %> 
	<% else %>
		<%= render "layouts/nav_top_not_signed_in" if !(controller.controller_name == "welcome" && controller.action_name == "wiki") %> 
	<% end %>

	<div id="ajaxloader" class="ajaxloader hidden"><%= image_tag("ajax-loader.gif") %></div>
	<h4 id="ajaxmsg" class="ajaxmsg hidden"><%= notice %></h4>

	<div class="container" role="main">
		<% if !notice.nil? %>
			<p id="notice"><%= notice %></p>
		<% elsif !alert.nil? %>
			<p id="alert"><%= alert %></p>
		<% end %>
		
		<%= yield %>
	</div><!-- /main -->

	<!-- nav bottom -->
	<%= render "layouts/nav_bottom" if !(controller.controller_name == "welcome" && controller.action_name == "wiki") %>
	

	<!-- notice/alert disappears after a few seconds -->
	<script>
		$(document).ready(function(){
			setTimeout(function(){
				$('#notice').fadeOut("slow", function(){
					$(this).remove();
				})	
			}, 4000);
		});

		$(document).ready(function(){
			setTimeout(function(){
				$('#alert').fadeOut("slow", function(){
					$(this).remove();
				})	
			}, 4000);
		});
	</script>

</body>
</html>